### ISSUE TITLE
Confusing error message in Ruby when enabling built in role support without specific role policy definitions

### ISSUE THREAD

**Issue by davidpelaez** [osohq/oso#1093]
Assuming I have classes for User, Org and OrgRole in my application and I'm starting to add roles to my application (no policies yet) with the following starting code:

```ruby
OSO = Oso.new

# Already defined elsewhere in my code as structs or ORM classes
OSO.register_class(User)
OSO.register_class(Org)
OSO.register_class(OrgRole)

# Carried from the quickstart, no role specific policies yet
OSO.register_class(Expense)
OSO.load_file('expenses.polar')

OSO.enable_roles # FAILS
```

That last line fails with a very confusing error `# Oso::Polar::InlineQueryFailedError: Inline query failed: resource(resource, name, actions, roles)`. This seems to be related to not having any mention in a policy of the classes related to roles.

When I load another policy (let's say `roles.polar`) with the content (note the Org class annotation):

```prolog
resource(_type: Org, "org", actions, roles) if
    actions = ["read", "create_repo"] and
    roles = {
        member: {
            permissions: ["read"],
        },
        owner: {
            permissions: ["read", "create_repo"],
        }
    };
```

The error now changes and it's much more helpful pointing me at the problem:

```
Oso::Polar::RolesValidationError: Oso Roles Validation Error: 
Need to define `actor_has_role_for_resource(actor, role_name, resource)` predicate to use Oso Roles.
Make sure to load policy before calling Oso.enable_roles().
```

I'm registering this because built in solutions like `enable_roles` seem to be very relevant to the Oso value proposition and providing a clearer error or instructions would help new users and provide a smoother flow. 

The ideal solution would be to have a clearer error to replace the `Oso::Polar::InlineQueryFailedError` when beginning with the setup. Maybe just a matter of phrasing on the error would help or just an explanation on the documentation to make it searchable. However, I'm leaving it open here because I don't really have a lot of context to propose a better solution.

**Comment by gkaemmer** [comment]
Hey @davidpelaez! Thanks for the report. Agreed that the errors here are a bit unwieldy. We do want to validate the roles configuration, but it does seem like the first error `Oso::Polar::InlineQueryFailedError` should in fact also be another `Oso::Polar::RolesValidationError` with a clearer message like:

```
Oso::Polar::RolesValidationError: Oso Roles Validation Error:
No `resource(type, name, actions, roles)` rule found in your policy. To use Oso Roles, you must define at least one resource rule like this:

resource(_type: Org, "org", actions, roles) if
    actions = ["read", "create_repo"] and
    roles = {
        member: {
            permissions: ["read"],
        },
        owner: {
            permissions: ["read", "create_repo"],
        }
    };

If you do already have a resource rule defined, make sure to load your policy before calling Oso.enable_roles().
```

It may not be immediate, but I'll see if we can get this change done in one of the next few releases.

**Comment by gj** [comment]
Hey @davidpelaez, we replaced this built-in roles feature in [the 0.20 release](https://www.osohq.com/post/release-oso-0-20) with a new syntax (and new, more helpful error messages). If you have any questions or thoughts about the new feature, we'd love to hear them!

Here's a guide that introduces the updated syntax: https://docs.osohq.com/guides/rbac.html
