### ISSUE TITLE
`AttributeError: 'str' object has no attribute 'query'` using the new enforcer interface

### ISSUE THREAD

**Issue by fullonic** [osohq/oso#1117]
Hey, thank you for this great framework :smiley: 

I'm trying the new [enforcer api](https://docs.osohq.com/python/guides/enforcement/enforcer.html) but I'm having the following error:
```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".../.venv/lib/python3.9/site-packages/oso/enforcer.py", line 61, in authorize
    if not self.policy.query_rule_once("allow", actor, action, resource):
  File ".../.venv/lib/python3.9/site-packages/polar/polar.py", line 223, in query_rule_once
    next(self.query(Predicate(name=name, args=args), **kwargs))
AttributeError: 'str' object has no attribute 'query'
```
I took my working oso setup and adapted to the new way (using Policy and Enforcer), and instead of calling `oso.is_allowed(user, action, resource)` now I'm doing `oso.authorize(user, action, resource)`
I checked the value of `self` at `polar/polar.py", line 223` and in fact, is of type string with value `allow`. 
Is this an issue or I'm missing something? 

Thanks for you help

**Comment by gkaemmer** [comment]
Hey @fullonic! Thanks for the report.

Trying to get a sense of how to reproduce this. It looks like for some reason `self.policy.query_rule_once` is not getting properly bound to an instance of `Policy`.

How are you constructing your Policy/Enforcer? I can imagine this happening if you construct your enforcer and pass the `Policy` class like this:
```
oso = Enforcer(Policy)
```
Instead of:
```
oso = Enforcer(policy)
```

**Comment by fullonic** [comment]
Hey @gkaemmer. Thanks for your help. Indeed, that was my mistake!! I'm closing this issue. Cheers!

**Comment by gkaemmer** [comment]
Cheers!

@fullonic While I have you, I should mention that the `Enforcer` class is a preview API, and we're merging it with the `Oso` class in the next release. (See #1119)

That means all the methods from `Enforcer` (`authorize`, `authorize_request`, etc) will instead be methods on `Oso`:
```python
oso = Oso()
oso.register_class(...)
oso.load_file(...)

# later

oso.authorize(actor, "read", resource)
```

Something to be aware of when updating off of `0.20.0-beta` -- apologies for the breaking change!

**Comment by fullonic** [comment]
@gkaemmer thanks for the tip
