### ISSUE TITLE
POLAR_LOG=0 should disable tracing

### ISSUE THREAD

**Issue by alexhafner** [osohq/oso#1121]
The documentation indicates that POLAR_LOG=1 enables tracing. Intuitively you would think that POLAR_LOG=0 disables tracing, particularly if you use the setting in a dotfile/docker-compose.yaml etc.

However, it seems that POLAR_LOG just needs to be set to anything to enable tracing, and to be unset to disable tracing. I've tested this with the go, node, python and rust libraries, and it's the same with all four:

Here's an example using the node library:

```
❯ which oso
/Users/alexhafner/.volta/bin/oso
❯ echo $POLAR_LOG
0
❯ oso
query> 1+2=3
[debug]   QUERY: 1 + 2 = _op_1 and _op_1 = 3, BINDINGS: {}
[debug]     QUERY: 1 + 2 = _op_1, BINDINGS: {}
[debug]     QUERY: _op_1 = 3, BINDINGS: {_op_1 = 3}
true
query> %
❯ unset POLAR_LOG
❯ oso
query> 1+2=3
true
query> %
❯ export POLAR_LOG=foo
❯ oso
query> 1+2=3
[debug]   QUERY: 1 + 2 = _op_1 and _op_1 = 3, BINDINGS: {}
[debug]     QUERY: 1 + 2 = _op_1, BINDINGS: {}
[debug]     QUERY: _op_1 = 3, BINDINGS: {_op_1 = 3}
true
query>
```

This was tested on main while reviewing the changes from https://github.com/osohq/oso/pull/1115

It would be helpful for developers if tracing could be disabled by setting POLAR_LOG=0.

**Comment by leina05** [comment]
Hey @alexhafner, thanks for opening this. This sounds like a reasonable change so we'll try to address it in an upcoming release.

**Comment by leina05** [comment]
Also, in case you're interested in making the change yourself, the `POLAR_LOG` check happens here: https://github.com/osohq/oso/blob/4af66a00a81b3df3fb5f3122774ac933a0e376cf/polar-core/src/vm.rs#L316. We only check that the variable is set, which is why `POLAR_LOG=0` doesn't disable tracing. Happy to answer questions on Slack if you decide to work on it.

**Comment by alexhafner** [comment]
Hi Leina - sure, I'll take it 😄

**Comment by gj** [comment]
> Hi Leina - sure, I'll take it 😄

That's awesome!

The desired behavior is as follows:

- `POLAR_LOG=now` -> **[remains unchanged]** a special value for internal development / testing
- `POLAR_LOG=0` and `POLAR_LOG=off` -> become the *only* ways to explicitly disable logging (logging should still be off by default by simply not setting the `POLAR_LOG` environment variable)
- `POLAR_LOG=<anything else>` -> **[remains unchanged]** enable query logging

Thank you for contributing!

**Comment by alexhafner** [comment]
Hi there, I've made some progress on this, and tested it in our experimental docker image https://github.com/appsmode/oso-docker-polyglot against 6 languages - the changes looks good except for Javascript - I need to look into why this does not behave as expected, I guess we've got something wrong in how we rebuild the library after the change. More to come ;-)

**Comment by gj** [comment]
@alexhafner You're a hero for https://github.com/appsmode/oso-docker-polyglot!

**Comment by gj** [comment]
Hey @alexhafner, how's it going with this? Is there anything we can do to support you?

**Comment by alexhafner** [comment]
Hi @gj - I'll pick that up again shortly with the latest release - was a bit busy in my day jobs ;-) - if I still get issues with the javascript tests that I can't figure out, I'll come back to you. Cheers

**Comment by alexhafner** [comment]
So, done - I had to modify the wasm-specific logic for environment variables and that took care of the javascript errors. There was also a bit of developer messaging code in Python that needed to take care of the additional values.
