### ISSUE TITLE
sqlalchemy-oso missing `py.typed`

### ISSUE THREAD

**Issue by alk3mist** [osohq/oso#1219]
Hi, is there any reason `py.typed` is not included in the `sqlalchemy-oso` package?

I see the typecheck command in [Makefile](https://github.com/osohq/oso/blob/199848db250bb824d9a6567a55a6e1528454495b/languages/python/sqlalchemy-oso/Makefile#L28) and `py.typed` [added](https://github.com/osohq/oso/blob/199848db250bb824d9a6567a55a6e1528454495b/languages/python/oso/setup.py#L70) to `oso/polar`.

**Comment by leina05** [comment]
Hi @alk3mist, I think this is just an oversight. We can add `py.typed` to `sqlalchemy-oso` in the next release.

**Comment by alk3mist** [comment]
`package_data={"sqlalchemy-oso": ["py.typed"]},` -> `package_data={"sqlalchemy_oso": ["py.typed"]},`

**Comment by gj** [comment]
@alk3mist would you mind submitting a PR for that change?

**Comment by samscott89** [comment]
https://github.com/osohq/oso/pull/1248

**Comment by alk3mist** [comment]
Sorry @samscott89 didn't see your comment yesterday. And yes, that would be the right way to contribute. I recently faced the same problem. Package settings in Python are not always obvious. Thanks for the fix.

**Comment by samscott89** [comment]
> 
> 
> Sorry @samscott89 didn't see your comment yesterday. And yes, that would be the right way to contribute. I recently faced the same problem. Package settings in Python are not always obvious. Thanks for the fix.

Thanks for following up and reporting!
