### ISSUE TITLE
[js] Can't use nested attributes of property if object is instanciated in polar (e.g. in inline-queries)

### ISSUE THREAD

**Issue by rradczewski** [osohq/oso#1242]
I'm using `oso@0.21.0` with `node@v14.17.0` (although it's the same with `typescript@4.4.3` and `node@16`).

Given a class with a nested property, e.g. `class JWT { constructor(ext) { this.ext = ext; } }`, (used like e.g. `new JWT({email: 'foo@bar', groups: []})` an instance created in JavaScript will properly return any nested properties of `ext`, but an instance created inside of polar will evaluate `ext` to `{}`.

https://github.com/FINVIA/oso-js-dict-issue/ contains two examples, one with a specific use-case, and one that I imagine narrows down the issue:

[`usecase.polar`](https://github.com/FINVIA/oso-js-dict-issue/blob/main/usecase.polar#L26) - The second inline-query will fail, and the message will look as follows. The same query in JS works just fine: https://github.com/FINVIA/oso-js-dict-issue/blob/main/usecase.js#L28

<details>
<summary>Debug Output</summary>
<pre>
<code>
[debug]   QUERY: new (JWT("anAdmin", {groups: ["HumanAdmin"]}), _instance_129) and new (AResource("anotherUser"), _instance_130) and allow(_instance_129, "read", _instance_130), BINDINGS: {}
[debug]     QUERY: new (JWT("anAdmin", {groups: ["HumanAdmin"]}), _instance_129), BINDINGS: {}
[debug]     QUERY: new (AResource("anotherUser"), _instance_130) and allow(_instance_129, "read", _instance_130), BINDINGS: {_instance_129 = JWT("anAdmin", {groups: ["HumanAdmin"]})}
[debug]       QUERY: new (AResource("anotherUser"), _instance_130), BINDINGS: {}
[debug]       QUERY: allow(_instance_129, "read", _instance_130), BINDINGS: {_instance_129 = JWT("anAdmin", {groups: ["HumanAdmin"]}), _instance_130 = AResource("anotherUser")}
[debug]         APPLICABLE_RULES:
[debug]           allow(actor, action, resource) if has_permission(actor, action, resource);
[debug]         RULE: allow(actor, action, resource) if has_permission(actor, action, resource);
[debug]           QUERY: has_permission(_actor_134, _action_135, _resource_136), BINDINGS: {_resource_136 = AResource("anotherUser"), _action_135 = "read", _actor_134 = JWT("anAdmin", {groups: ["HumanAdmin"]})}
[debug]             APPLICABLE_RULES:
[debug]               has_permission(actor: Actor{}, "read", aresource: AResource{}) if has_role(actor, "owner", aresource);
[debug]               has_permission(actor: Actor{}, "read", aresource: AResource{}) if has_role(actor, "admin", aresource);
[debug]             RULE: has_permission(actor: Actor{}, "read", aresource: AResource{}) if has_role(actor, "owner", aresource);
[debug]             MATCHES: _actor_145 matches Actor{}, BINDINGS: {_actor_145 = JWT("anAdmin", {groups: ["HumanAdmin"]})}
[debug]             MATCHES: _actor_145 matches JWT{}, BINDINGS: {_actor_145 = JWT("anAdmin", {groups: ["HumanAdmin"]})}
[debug]             MATCHES: JWT("anAdmin", {groups: ["HumanAdmin"]}) matches JWT{}, BINDINGS: {}
[debug]             MATCHES: JWT("anAdmin", {groups: ["HumanAdmin"]}) matches {}, BINDINGS: {}
[debug]             MATCHES: _aresource_146 matches AResource{}, BINDINGS: {_aresource_146 = AResource("anotherUser")}
[debug]             MATCHES: AResource("anotherUser") matches AResource{}, BINDINGS: {}
[debug]             MATCHES: AResource("anotherUser") matches {}, BINDINGS: {}
[debug]               QUERY: has_role(_actor_145, "owner", _aresource_146), BINDINGS: {_aresource_146 = AResource("anotherUser"), _actor_145 = JWT("anAdmin", {groups: ["HumanAdmin"]})}
[debug]                 APPLICABLE_RULES:
[debug]                   has_role(user: JWT{}, "owner", res: AResource{}) if _value_1 = _value_2 and user.sub = _value_1 and res.ownerId = _value_2;
[debug]                 RULE: has_role(user: JWT{}, "owner", res: AResource{}) if _value_1 = _value_2 and user.sub = _value_1 and res.ownerId = _value_2;
[debug]                 MATCHES: _user_157 matches JWT{}, BINDINGS: {_user_157 = JWT("anAdmin", {groups: ["HumanAdmin"]})}
[debug]                 MATCHES: JWT("anAdmin", {groups: ["HumanAdmin"]}) matches JWT{}, BINDINGS: {}
[debug]                 MATCHES: JWT("anAdmin", {groups: ["HumanAdmin"]}) matches {}, BINDINGS: {}
[debug]                 MATCHES: _res_158 matches AResource{}, BINDINGS: {_res_158 = AResource("anotherUser")}
[debug]                 MATCHES: AResource("anotherUser") matches AResource{}, BINDINGS: {}
[debug]                 MATCHES: AResource("anotherUser") matches {}, BINDINGS: {}
[debug]                   QUERY: __value_1_159 = __value_2_160 and _user_157.sub = __value_1_159 and _res_158.ownerId = __value_2_160, BINDINGS: {_res_158 = AResource("anotherUser"), _user_157 = JWT("anAdmin", {groups: ["HumanAdmin"]})}
[debug]                     QUERY: __value_1_159 = __value_2_160 and _user_157.sub = __value_1_159, BINDINGS: {_user_157 = JWT("anAdmin", {groups: ["HumanAdmin"]})}
[debug]                       QUERY: __value_1_159 = __value_2_160, BINDINGS: {}
[debug]                       QUERY: _user_157.sub = __value_1_159, BINDINGS: {_user_157 = JWT("anAdmin", {groups: ["HumanAdmin"]}), __value_1_159 = __value_2_160}
[debug]                         QUERY: JWT("anAdmin", {groups: ["HumanAdmin"]}).sub = __value_1_159, BINDINGS: {__value_1_159 = __value_2_160}
[debug]                           LOOKUP: JWT("anAdmin", {groups: ["HumanAdmin"]}).sub()
[debug]                           => "anAdmin"
[debug]                     QUERY: _res_158.ownerId = __value_2_160, BINDINGS: {__value_2_160 = "anAdmin", _res_158 = AResource("anotherUser")}
[debug]                       QUERY: AResource("anotherUser").ownerId = __value_2_160, BINDINGS: {__value_2_160 = "anAdmin"}
[debug]                         LOOKUP: AResource("anotherUser").ownerId()
[debug]                         => "anotherUser"
[debug]                         BACKTRACK
[debug]             RULE: has_permission(actor: Actor{}, "read", aresource: AResource{}) if has_role(actor, "admin", aresource);
[debug]             MATCHES: _actor_147 matches Actor{}, BINDINGS: {_actor_147 = JWT("anAdmin", {groups: ["HumanAdmin"]})}
[debug]             MATCHES: _actor_147 matches JWT{}, BINDINGS: {_actor_147 = JWT("anAdmin", {groups: ["HumanAdmin"]})}
[debug]             MATCHES: JWT("anAdmin", {groups: ["HumanAdmin"]}) matches JWT{}, BINDINGS: {}
[debug]             MATCHES: JWT("anAdmin", {groups: ["HumanAdmin"]}) matches {}, BINDINGS: {}
[debug]             MATCHES: _aresource_148 matches AResource{}, BINDINGS: {_aresource_148 = AResource("anotherUser")}
[debug]             MATCHES: AResource("anotherUser") matches AResource{}, BINDINGS: {}
[debug]             MATCHES: AResource("anotherUser") matches {}, BINDINGS: {}
[debug]               QUERY: has_role(_actor_147, "admin", _aresource_148), BINDINGS: {_actor_147 = JWT("anAdmin", {groups: ["HumanAdmin"]}), _aresource_148 = AResource("anotherUser")}
[debug]                 APPLICABLE_RULES:
[debug]                   has_role(user: JWT{}, "admin", _res: AResource{}) if user.ext = _value_3 and _value_3.groups = _value_4 and group in _value_4 and allowed_group in ["HumanAdmin", "MachineAdmin"] and group = allowed_group;
[debug]                 RULE: has_role(user: JWT{}, "admin", _res: AResource{}) if user.ext = _value_3 and _value_3.groups = _value_4 and group in _value_4 and allowed_group in ["HumanAdmin", "MachineAdmin"] and group = allowed_group;
[debug]                 MATCHES: _user_175 matches JWT{}, BINDINGS: {_user_175 = JWT("anAdmin", {groups: ["HumanAdmin"]})}
[debug]                 MATCHES: JWT("anAdmin", {groups: ["HumanAdmin"]}) matches JWT{}, BINDINGS: {}
[debug]                 MATCHES: JWT("anAdmin", {groups: ["HumanAdmin"]}) matches {}, BINDINGS: {}
[debug]                 MATCHES: __res_176 matches AResource{}, BINDINGS: {__res_176 = AResource("anotherUser")}
[debug]                 MATCHES: AResource("anotherUser") matches AResource{}, BINDINGS: {}
[debug]                 MATCHES: AResource("anotherUser") matches {}, BINDINGS: {}
[debug]                 QUERY: _user_175.ext = __value_3_177 and __value_3_177.groups = __value_4_178 and _group_179 in __value_4_178 and _allowed_group_180 in ["HumanAdmin", "MachineAdmin"] and _group_179 = _allowed_group_180, BINDINGS: {_user_175 = JWT("anAdmin", {groups: ["HumanAdmin"]})}
[debug]                   QUERY: _user_175.ext = __value_3_177 and __value_3_177.groups = __value_4_178 and _group_179 in __value_4_178, BINDINGS: {_user_175 = JWT("anAdmin", {groups: ["HumanAdmin"]})}
[debug]                     QUERY: _user_175.ext = __value_3_177, BINDINGS: {_user_175 = JWT("anAdmin", {groups: ["HumanAdmin"]})}
[debug]                       QUERY: JWT("anAdmin", {groups: ["HumanAdmin"]}).ext = __value_3_177, BINDINGS: {}
[debug]                         LOOKUP: JWT("anAdmin", {groups: ["HumanAdmin"]}).ext()
[debug]                         => {}
[debug]                     QUERY: __value_3_177.groups = __value_4_178 and _group_179 in __value_4_178, BINDINGS: {__value_3_177 = {}}
[debug]                       QUERY: __value_3_177.groups = __value_4_178, BINDINGS: {__value_3_177 = {}}
[debug]                         QUERY: {}.groups = __value_4_178, BINDINGS: {}
[debug]                           BACKTRACK
[debug]                           HALT
</code>
</pre>
</details>

[`minimalist.polar`](https://github.com/FINVIA/oso-js-dict-issue/blob/main/minimalist.polar#L3) narrows down the issue I hope.

Here's a snippet on how to reproduce the issue:

```js
const { Oso } = require("oso");

class User {
    constructor(opts) {
        this.opts = opts;
    }
}

const run = async () => {
    const oso = new Oso();
    oso.registerClass(User);
    await oso.loadStr(`
actor User {}

?= (new User(1)).opts = 1;
?= (new User({foo: 1})).opts.foo = 1;
    `);
};

run();
```

And the debug output to that:

```
[debug]   QUERY: new (User({foo: 1}), _instance_1) and _instance_1.opts = _value_2 and _value_2.foo = _value_3 and _value_3 = 1, BINDINGS: {}
[debug]     QUERY: new (User({foo: 1}), _instance_1), BINDINGS: {}
[debug]     QUERY: _instance_1.opts = _value_2 and _value_2.foo = _value_3 and _value_3 = 1, BINDINGS: {_instance_1 = User({foo: 1})}
[debug]       QUERY: _instance_1.opts = _value_2, BINDINGS: {_instance_1 = User({foo: 1})}
[debug]         QUERY: User({foo: 1}).opts = _value_2, BINDINGS: {}
[debug]           LOOKUP: User({foo: 1}).opts()
[debug]           => {}
[debug]       QUERY: _value_2.foo = _value_3 and _value_3 = 1, BINDINGS: {_value_2 = {}}
[debug]         QUERY: _value_2.foo = _value_3, BINDINGS: {_value_2 = {}}
[debug]           QUERY: {}.foo = _value_3, BINDINGS: {}
[debug]             BACKTRACK
[debug]             HALT
(node:194876) UnhandledPromiseRejectionWarning: Error: Inline query failed: (new User({foo: 1})).opts.foo = 1 at line 5, column 3
    at Oso.checkInlineQueries (./oso-js-dicts/node_modules/oso/dist/src/Polar.js:173:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async run (./oso-js-dicts/minimalist.js:12:5)
```

**Comment by samscott89** [comment]
Hey! Thanks for opening this. We've found the source of the problem -- as JSON serialization issue when a dictionary goes Polar -> JS -> Polar. We're working on a fix ASAP.

**Comment by samscott89** [comment]
Hey @rradczewski, thanks for raising this and helping reproduce it! This helped catch a nasty discrepancy between the core and the node library.

We typically release on a 3 week cadence, the last just went out earlier this week. Is this blocking you from making progress on your project?

**Comment by rradczewski** [comment]
Hi @samscott89, no rush from my side, I'll just keep the tests as regular jest tests until you release the next version :+1: 

Thanks again for fixing it so quickly!
