### ISSUE TITLE
Can get_checked_permissions pass in the authorized_session?

### ISSUE THREAD

**Issue by radiantone** [osohq/oso#1263]
Hi,
  I got a chicken and the egg issue here. I create my `authorized_session` and point it to my `get_checked_permissions` function, but inside there I need a reference to the`authorized_session` to do lookups and build the permissions object. 
  
  Suggestion: Oso can pass in the `authorized_session` instance to `get_checked_permissions` ?

**Comment by gkaemmer** [comment]
@radiantone Closing this issue for now. Don't hesitate to comment and reopen if you have some examples of where this might be useful. Depending on the example, I bet we could come up with another way of solving the problem.
 
For most use cases I can think of, we don't need access to the authorized session (or any session at all) during `get_checked_permissions`, as it's designed to return a static result per-endpoint.
