### ISSUE TITLE
Small typo in documentation

### ISSUE THREAD

**Issue by amarshall45676** [osohq/oso#1275]
First of all just wanted to say thank you for the wonderful docs! Just reading through then and found a small typo I thought I would point out. One of the examples uses "Atemis" instead of "Artemis" so should be a quick fix.
I found the MD file that can be modified to fix the typo: https://github.com/osohq/oso/blob/main/docs/content/any/learn/polar-foundations.md

The example that has the typo looks like this
`>> mother("Atemis", mother)`

**Comment by michal-borsiak** [comment]
I can take care of this one. Please assign that ticket to me.
