### ISSUE TITLE
__dirname is not defined in ES module scope

### ISSUE THREAD

**Issue by pheuter** [osohq/oso#1309]
`ReferenceError: __dirname is not defined in ES module scope`

Unfortunately, oso appears to have trouble running when I build it as part of an ESM project because it references `__dirname` in certain parts of the code below:

```js
// oso@0.22.0/node_modules/oso/dist/src/polar_wasm_api.js
var path2 = __require("path").join(__dirname, "polar_wasm_api_bg.wasm");
```

In my own code, where I load the `.polar` files, I work around this issue using the ESM recommended approach:

```ts
import path from 'path';
import { fileURLToPath } from 'url';

const dirname = path.dirname(fileURLToPath(import.meta.url));

await oso.loadFiles([path.resolve(dirname, 'main.polar')]);
```

**Comment by gj** [comment]
Fascinating! Thanks for pointing this out @pheuter. It sounds like you're able to work around the `__dirname` issue when specifying `.polar` files to load, but you'd have to modify the distributed package in order to work around the internal usage of `__dirname` — is that accurate?

**Comment by pheuter** [comment]
@gj Exactly, hence the hard block.

**Comment by pheuter** [comment]
Updated issue description, removed snippet that was irrelevant to oso, think it's just one place where `__dirname` is used that the runtime complains about.

**Comment by gj** [comment]
@pheuter are you able to provide a minimal reproduction (in a gist or repo) that I could use to try to reproduce the issue? Probably comprised of the toolchain you're using to build your ESM project + a single file that imports Oso.

**Comment by pheuter** [comment]
@gj As I started working on the repro I was able to figure out that I should be declaring `oso` (as well as some other deps) as [external](https://esbuild.github.io/api/#external) instead of bundling it and causing issues.

**Comment by pheuter** [comment]
I'm using SvelteKit, which means moving `oso` from `devDependencies` to `dependencies`.

**Comment by gj** [comment]
Oh great! So everything's working now?

**Comment by pheuter** [comment]
Yes, it now _slightly_ complicates the `oso.loadFiles` call since the `main.polar` file isn't automatically copied over to the build directory, but that's def not a hard blocker anymore, esp since `oso.loadStr()` exists.

**Comment by pheuter** [comment]
Appreciate the quick response 👍
