### ISSUE TITLE
implement authorizedResources for java 

### ISSUE THREAD

**Issue by zeekrs** [osohq/oso#1349]
Are there plans to implement authorizedResources for java

**Comment by gw000** [comment]
Hi @zeekrs ! That is the plan, but we don't have an exact timeline yet. We're still working on stabilizing the API and making everything work reliably in the currently supported languages, and after that we'll port it to the remaining libraries.

**Comment by zeekrs** [comment]
> Hi @zeekrs ! That is the plan, but we don't have an exact timeline yet. We're still working on stabilizing the API and making everything work reliably in the currently supported languages, and after that we'll port it to the remaining libraries.

Thanks for your reply
