### ISSUE TITLE
Missing wheels for python 3.10

### ISSUE THREAD

**Issue by kumekay** [osohq/oso#1354]
The most recent PyPI release for [OSO 0.22.1](https://pypi.org/project/oso/0.22.1/#files)   is still missing python 3.10 wheels (and there is no source distribution) so it's impossible to use with the latest stable python.

https://github.com/pypa/cibuildwheel supports python 3.10 starting 2.1.3 releae

**Comment by kumekay** [comment]
Ough, I see the relevant PR is  already merged:
https://github.com/osohq/oso/pull/1350

Do you have any timeline for the new wheels on PyPI?

**Comment by saolsen** [comment]
Should be published on Tuesday with the next release, I can publish one now for you though. Which operating system do you need it for?

**Comment by kumekay** [comment]
> Should be published on Tuesday with the next release, I can publish one now for you though. Which operating system do you need it for?

Great, thank you!

We are on Debian bullseye amd64

**Comment by saolsen** [comment]
[oso-0.22.1.zip](https://github.com/osohq/oso/files/7478143/oso-0.22.1.zip)

**Comment by saolsen** [comment]
I also uploaded it to pypi so you should be able to `pip install` it

**Comment by kumekay** [comment]
> I also uploaded it to pypi so you should be able to `pip install` it

Thank you so much, it installs fine!

I'll close this issue, because as you said on Tuesday  it will be on all platforms.
