### ISSUE TITLE
[docs] The syntax guide for Polar on Notion is not accessible

### ISSUE THREAD

**Issue by micalevisk** [osohq/oso#1482]
https://github.com/osohq/oso/blob/7cd4e87e816349842f1fe72d344fb288cf3d57c9/docs/content/any/learn/polar-foundations.md#L11

When I go to this page:

https://www.notion.so/Concepts-The-Polar-Language-0c59f78527bb470bbefb173ebf85ed69

I got this permission(?) error:

![image](https://user-images.githubusercontent.com/13461315/149006645-06ec4388-d4e6-4f11-bc90-ad62f9e5876e.png)

**Comment by gj** [comment]
Thanks for pointing this out @micalevisk! Will have a PR fix up shortly.

**Comment by gj** [comment]
(Also in the meantime the syntax guide is located [here](https://docs.osohq.com/reference/polar/polar-syntax.html).)
