### ISSUE TITLE
VSCode Oso extension not published on open-vsx

### ISSUE THREAD

**Issue by fairingrey** [osohq/oso#1524]
It would be nice to have the VSCode Oso extension published on [open-vsx](https://open-vsx.org/) to make it easier for users like myself who don't have access to Microsoft Marketplace (using the code-oss flavor).

Thanks!

**Comment by samscott89** [comment]
Hi @fairingrey! Thanks for opening an issue, and thanks for letting us know -- I hadn't heard about open-vsx before. Sounds like a great project.

**Comment by ramonsnir** [comment]
Hey @samscott89 . FYI: Gitpod isn't allowed by Microsoft to use Microsoft Marketplace, so without this being published to open-vsx my team can't use the extension.

Docs from Gitpod about this limitation: https://www.gitpod.io/docs/ides-and-editors/vscode-extensions#:~:text=If%20you%20cannot,maintained%20by%20Microsoft.

**Comment by ramonsnir** [comment]
If a future reader needs to get this extension working in Gitpod, here is the line we added to our [custom Docker image](https://www.gitpod.io/docs/config-docker) Dockerfile:

```dockerfile
# Build and package the Oso VS Code extension
RUN npm install --global yarn wasm-pack && cd /tmp/ && git clone --depth=1 https://github.com/osohq/oso/ \
  && cd oso/ && make CARGO_FLAGS=--release rust-build wasm-build \
  && cd polar-language-server && make CARGO_FLAGS=--release build && cd .. \
  && cd vscode/oso/ && npm install && yarn package \
  && mv oso.vsix ~/
# To install the Oso extension, add this task to .gitpod.yml:
# before: (gp await-port 23000 && code --install-extension ~/oso.vsix) & disown; exit
```

**Comment by gj** [comment]
Hey @fairingrey & @ramonsnir, we're going to look into getting the extension published on open-vsx within the next couple of weeks. Myself or @vrama628 will keep you apprised!

**Comment by vrama628** [comment]
Hi @fairingrey and @ramonsnir, thanks for bearing with us! The latest version of our VSCode extension is now published on Open VSX at https://open-vsx.org/extension/osohq/oso .
