### ISSUE TITLE
Add Polar to GitHub grammars list

### ISSUE THREAD

**Issue by micalevisk** [osohq/oso#1541]
Can you guys make a request (or even implement :smile:) on https://github.com/github/linguist to support Polar as a new language so we can get syntax highlighting from `.polar` files?

![image](https://user-images.githubusercontent.com/13461315/158695736-cf6b7793-4c00-432f-bf7a-caf0cb5e0f11.png)

**Comment by patrickod** [comment]
hey @micalevisk thanks for writing in 👋🏻 

this is something we have definitely considered in the past. The Github linguist repository imposes some usage/popularity thresholds which languages must past before they quality for inclusion. specifically they require that the extension be used in 200+ unique repositories, which we unfortunately do not meet at this moment.

we have been keeping eye on the usage stats over time and hope to submit as soon as we qualify - we agree it would be a much better experience to have the full syntax highlighting functionality when browsing policies on Github!

**Comment by ngouy** [comment]
the criteria may be about to change:
https://github.com/github/linguist/issues/5756
And you are probably close to meeting the 200+ repos
Also it's a weird requirement as the search cannot index private repo, which may be a good part of your users...

**Comment by gneray** [comment]
Looking at this again

**Comment by samscott89** [comment]
https://github.com/github/linguist/pull/6101

**Comment by samscott89** [comment]
Done! It's now live!

**Comment by ngouy** [comment]
let's go

Thanks a lot!! You guys are awesome
