### ISSUE TITLE
When trying to run oso-oso gem I get an error

### ISSUE THREAD

**Issue by evolfo** [osohq/oso#1550]
I saw a previous post with this error (https://github.com/osohq/oso/issues/1525), however I have the most recent version of oso-oso so that didn't resolve my issue. 

I'm running OS 12.2.1 with a M1 chip.

`LoadError: Could not open library '/Users/{uname}/.rvm/gems/ruby-3.0.2/gems/oso-oso-0.26.0/ext/oso-oso/lib/libpolar.dylib': dlopen(/Users/{uname}/.rvm/gems/ruby-3.0.2/gems/oso-oso-0.26.0/ext/oso-oso/lib/libpolar.dylib, 0x0005): tried: '/Users/{uname}/.rvm/gems/ruby-3.0.2/gems/oso-oso-0.26.0/ext/oso-oso/lib/libpolar.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/libpolar.dylib' (no such file), '/usr/lib/libpolar.dylib' (no such file)`

**Comment by saolsen** [comment]
Hey, unfortunately the ruby gem doesn't support apple M1 chips yet. You can run ruby under Rosetta or you can try building the library from source.

**Comment by gj** [comment]
Closing in favor of #1525

**Comment by evolfo** [comment]
I was running Ruby under Rosetta when I experienced this error.
