### ISSUE TITLE
[Java] Mac OSX ARM support for jar that is hosted on Central

### ISSUE THREAD

**Issue by easen-amp** [osohq/oso#1597]
The JAR that is hosted on [Central](https://repo1.maven.org/maven2/), isn't bundled with the multi-arch dylib (`libpolar-fat.dylib`).

https://github.com/osohq/oso/blob/e8c7e6d097bb5d796f0430fd208a9ae6a1d39c8e/.github/workflows/publish.yml#L69

**Comment by uncommoncense** [comment]
This is resolved by https://github.com/osohq/oso/pull/1608
