### ISSUE TITLE
Type alias in struct definition behavior (Go)

### ISSUE THREAD

**Issue by adrianplavka** [osohq/oso#1628]
I am writing a simple rule for authorization of a current user using Oso's `allow` directive. User's roles are represented as a simple string, containing a single value of user's role. I would like to ask for a clarification on how type aliases work using this library, as I am having a hard time passing a simple authorization logic.

Given a definition of struct:

```go
package ent

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// Password holds the value of the "password" field.
	Password string `json:"password,omitempty"`
	// Role holds the value of the "role" field.
	Role user.Role `json:"role,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges UserEdges `json:"edges"`
}
```

Take a look at the `Role` attribute - it's type is `user.Role`, which is simply a type alias to a string:

```go
package user

type Role string
```

Registering this struct definition using Oso's method:

```go
oso.RegisterClass(reflect.TypeOf(ent.User{}), nil)
```

Defining a Polar schema:
```
allow(actor: User, _action, _resource) if actor.Role == "admin";
```

Running a simple authorization against this model will result in `Authorize` method to return an error:
```go
currentUser := &User{ Role: "admin" }
oso.Authorize(currentUser, "create", nil)
```

I've also run the code using `POLAR_LOG=info` which would show me that it found a match for this rule, but it was falsy.

Debugging a Polar schema with this block:
```
allow(actor: User, _action, _resource) if print(actor.Role);
```
would print to the console `user.Roleadmin TYPE 'user.Role'`. I am not sure on how to pattern match against this kind of value - which brings me to the question, if this is intended behavior with a solution, or a bug?

Thanks for an answer and for creating this interesting library!

**Comment by samscott89** [comment]
Hey @adrianplavka!

You should be able to register the class in the same way as you did with the `User` class -- by constructing an instance of the type (even if its empty!) and passing it in. For example:

```go
oso.RegisterClass(Role(""), nil )
```

You might want to also pass in a constructor too:

```go
oso.RegisterClass(Role(""), func (s string) Role { return Role(s) } )
```

Which would let you construct instance in your policy:

```
allow(actor: User, _action, _resource) if actor.Role = new Role("admin");
```

or alternatively, you could register some of those as constants:

```go
oso.RegisterConstant(Role("admin"), "Admin")
```

```
allow(actor: User, _action, _resource) if actor.Role = Admin;
```

Hope that helps! Let me know if you have any follow up questinos

**Comment by adrianplavka** [comment]
Thanks for the clarification, I've updated the code and it works as intended!
