### ISSUE TITLE
Slower Oso queries with increasing thread count

### ISSUE THREAD

**Issue by alexpearce** [osohq/oso#1643]
I'm using Oso to authorise requests and actions in a FastAPI application and see poor Oso performance scaling with increasing thread count. 

FastAPI uses the [`concurrent.futures.ThreadPoolExecutor`](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor) to process each request in its own thread. In my production profiling I see that Oso calls take a proportionally larger fraction of the total request time as the number of concurrent requests increases.

The following synthetic benchmark calls `Oso.authorize_request` 1000 times sequentially in each of 1 or more threads:

<details>
<summary>Python script</summary>

```python
"""Benchmark demonstrating Oso's scaling across threads.

Create an environment:

    python3 -m venv venv
    . venv/bin/activate
    pip install oso

Run:

    python3 oso_threading.py
"""
import concurrent.futures
import time

from oso.oso import Oso


class Request:
    def __init__(self, scope):
        self.scope = scope


class Token:
    pass


def authorize_requests(oso=None, n=1_000):
    if oso is None:
        oso = create_oso()

    token = Token()
    request= Request(
        scope=dict(
            type="http",
            endpoint={
                "_required_scopes": None,
            },
        ),
    )

    start = time.perf_counter_ns()
    for _ in range(n):
        oso.authorize_request(token, request)
    end = time.perf_counter_ns()

    delta_ns = end - start
    per_call_ns = delta_ns / n
    print(f"ncalls={n}; total={delta_ns / 1e9:.3f} s; call/s={1e9 / per_call_ns:.1f}; time/call={per_call_ns / 1e3:.1f} µs")


def create_oso():
    oso = Oso()
    oso.register_class(Request)
    oso.register_class(Token)
    oso.load_files(["main.polar"])
    return oso
    
    
def benchmark():
    # Oso instance shared across all threads
    oso = create_oso()

    # Run `max_threads` tests, from 1 thread to `max_threads` threads
    max_threads = 6
    for workers in range(1, max_threads + 1):
        print(f"#threads={workers}")
        # In each test spawn `workers` workers, each executing the `authorize_requests` function
        with concurrent.futures.ThreadPoolExecutor(max_workers=workers) as executor:
            for _ in range(workers):
                # Set `oso=None` to create per-thread Oso
                executor.submit(authorize_requests, oso=None)


if __name__ == "__main__":
    benchmark()

```

</details>

The Polar rules are very simple:

<details>
<summary>Polar rules</summary>

```polar
allow_request(token: Token, request: Request) if
  # If the endpoint permits token-less access then no need to check the token
  allow_request(nil, request) or
  forall(scope in request.scope.endpoint._required_scopes, token.has_permission(scope));

allow_request(nil, request: Request) if
  request.scope.endpoint._required_scopes = nil;

allow_request(token: Token, _request: Request) if
  token.has_permission("sudo");
```
</details>

Running this in 1 thread and up to 6 threads shows the throughput gradually decreasing with increasing thread count:

```
#threads=1
ncalls=1000; total=0.149 s; call/s=6716.3; time/call=148.9 µs
#threads=2
ncalls=1000; total=0.271 s; call/s=3693.8; time/call=270.7 µs
ncalls=1000; total=0.272 s; call/s=3677.7; time/call=271.9 µs
#threads=3
ncalls=1000; total=0.475 s; call/s=2105.0; time/call=475.1 µs
ncalls=1000; total=0.483 s; call/s=2070.1; time/call=483.1 µs
ncalls=1000; total=0.485 s; call/s=2061.1; time/call=485.2 µs
#threads=4
ncalls=1000; total=0.687 s; call/s=1454.8; time/call=687.4 µs
ncalls=1000; total=0.696 s; call/s=1435.9; time/call=696.4 µs
ncalls=1000; total=0.697 s; call/s=1435.5; time/call=696.6 µs
ncalls=1000; total=0.697 s; call/s=1434.9; time/call=696.9 µs
#threads=5
ncalls=1000; total=0.911 s; call/s=1098.0; time/call=910.7 µs
ncalls=1000; total=0.916 s; call/s=1092.1; time/call=915.6 µs
ncalls=1000; total=0.919 s; call/s=1088.7; time/call=918.5 µs
ncalls=1000; total=0.918 s; call/s=1089.1; time/call=918.2 µs
ncalls=1000; total=0.923 s; call/s=1083.9; time/call=922.6 µs
#threads=6
ncalls=1000; total=1.163 s; call/s=859.8; time/call=1163.1 µs
ncalls=1000; total=1.165 s; call/s=858.4; time/call=1165.0 µs
ncalls=1000; total=1.171 s; call/s=854.2; time/call=1170.7 µs
ncalls=1000; total=1.180 s; call/s=847.2; time/call=1180.3 µs
ncalls=1000; total=1.178 s; call/s=849.2; time/call=1177.5 µs
ncalls=1000; total=1.177 s; call/s=849.3; time/call=1177.4 µs
```

This is on a 10-core M1 Pro.

The behaviour in the benchmark matches the profiles I have in production, where Oso calls take O(10 ms) when there are no concurrent requests, but O(100 ms) with concurrent requests.

Note that the default behaviour of the benchmark is to use a single, 'global' `Oso` instance shared across threads, but I see the same behaviour when creating an `Oso` instance per thread.

---

Are there any techniques for mitigating the scaling behaviour when using multiple threads? I'm not sure if this is a Python problem (GIL?) or an Oso problem (some process-level lock somewhere?), but either way any advice for improvements would be greatly appreciated!

**Comment by alexpearce** [comment]
> I'm seeing the same behaviour if I replace the Oso call with: …

Well, that safely rules out Oso as the root cause 😄

> I think you might want to instead try running FastAPI with a ASGI server

I do do that but perhaps there's a smarter configuration for my use-case.

Thank you very much for taking a look @samscott89! I'll close this issue and report back [in case](https://xkcd.com/979/) I discover any tips .

**Comment by alexpearce** [comment]
…having said that, when I replace the `oso.authorize_request` call with `assert 1 == 1`, I do _not_ reproduce the original results; the number of calls per second is pretty constant with the thread count.

So, will re-open just to see if we can agree on that!

**Comment by samscott89** [comment]
> …having said that, when I replace the `oso.authorize_request` call with `assert 1 == 1`, I do _not_ reproduce the original results; the number of calls per second is pretty constant with the thread count.
> 
> So, will re-open just to see if we can agree on that!

Yep, the line above was also needed to make it expensive enough to show up:

```
    start = time.perf_counter_ns()
    for _ in range(n):
        for _ in range(100000):
            assert 1 == 1
        # oso.authorize_request(token, request)
    end = time.perf_counter_ns()
```

> Because Python spawns 'regular' OS threads I think they can run across multiple cores (being scheduled on whatever the kernel places them on), however it is easy for those threads to be prevented from running in parallel due to Python's 'global interpreter lock', effectively negating the multithreading benefit.

That's interesting. What I ended up doing was watching `top` and I could only see Python using 1 CPU, so figured that was the cause.

**Comment by alexpearce** [comment]
I'm not worried about this at the moment and don't think there's enough information here for it to be useful in near-term so will close.
