### ISSUE TITLE
Add support for SQLAlchemy 2.0 in sqlalchemy-oso for Python

### ISSUE THREAD

**Issue by kkirsche** [osohq/oso#1667]
Last night, SQLAlchemy released 2.0 after multiple betas, release candidates, etc.

Migration Guide:
https://docs.sqlalchemy.org/en/20/changelog/migration_20.html

Release Tag:
https://github.com/sqlalchemy/sqlalchemy/releases/tag/rel_2_0_0

Changelog:
https://docs.sqlalchemy.org/en/20/changelog/changelog_20.html#change-2.0.0

**Comment by snstanton** [comment]
Is there any sort of timeframe for this work?  The latest release of SQLAlchemy 1.4 introduces a bunch of deprecation warnings which cannot be resolved without updating to a newer version of Flask-SQLAlchemy.  This problem is only going to get worse as more libraries move forward.

**Comment by kkirsche** [comment]
Great question, @snstanton — I'm not sure. I may take a look at this depending on what the response is like from the Oso team. Over the last couple of months, I've found things to be pretty quiet here as most of the their team seems to have gone to work on Oso Cloud. Just my observation though, I don't have any inside knowledge

**Comment by svendjo** [comment]
Is there any update on this? We need it too.

**Comment by nephi-dev** [comment]
same here, needing an update

**Comment by AbdealiLoKo** [comment]
We were looking for a better authorization architecture - and came across oso and have been impressed so far
But we have upgraded to sqla 2 and will need our auth to be compatible with sqla2

It would be great if the OSO team could comment on whether this is a "Won't fix" or "Planned"

**Comment by jedkass** [comment]
+1

**Comment by samscott89** [comment]
Hey all,

I've been looking into how feasible this would be, and tried a version of this available at at [`0.27.2rc0`](https://pypi.org/project/sqlalchemy-oso/0.27.2rc0/). This passes my tests, but I'm not sure of the full scope of changes. Would appreciate any feedback on those changes.

I also want to remind people that this package is [deprecated](https://www.osohq.com/docs/oss/getting-started/deprecation.html). But we're hoping sqlalchemy 2.0 support will give people a bit more time to make a plan.

**Comment by kkirsche** [comment]
Thank you, Sam, for your time and effort on this. I'm out of the office for a little bit on paternity leave but happy to try this out in our projects at work when I get back at the end of February 👍

This is extremely useful though and greatly appreciated. Excited to see the next phase of Oso 🐻

**Comment by kkirsche** [comment]
I ended up taking more time than I originally anticipated (which was nice), so I'm just coming back up to speed with what the team has been up to. Once I catch up, I'll evaluate this and share what I find. Thank you for your patience!

**Comment by samscott89** [comment]
We just published the above changes as 0.27.2. Thanks all for your patience.

**Comment by kkirsche** [comment]
Thanks Sam, initial tests are looking good for me. You guys rock!
