### ISSUE TITLE
Querying with an unbound variable does not return all possible expressions for recursive function

### ISSUE THREAD

**Issue by adrns** [osohq/oso#1668]
Hi, I've recently posted [a question on the oso slack](https://oso-oss.slack.com/archives/C017KSBTD4M/p1674811424956299), and was asked to post an issue. 

Given the polar rule
```
has_intersection(owned_labels, allowed_labels) if
  [first, *tail] = owned_labels and
  (has_intersection(tail) or first in allowed_labels);
```
Let's say `owned_labels` is assigned `["red", "green", "blue"]`, `allowed_labels` is unbound.

Then querying the vm with accepting expressions as result:

Expected result
result 1
`allowed_labels` -> Expression describing that "red" should be in `allowed_labels`
`owned_labels` -> the passed list
result 2
`allowed_labels` -> Expression describing that "green" should be in `allowed_labels`
`owned_labels` -> the passed list
result 3
`allowed_labels` -> Expression describing that "blue" should be in `allowed_labels`
`owned_labels` -> the passed list

Actual result
result 1
`allowed_labels` -> Expression describing that "red" should be in `allowed_labels`
`owned_labels` -> the passed list

I've [created a branch on a fork from oso-java-quickstart](https://github.com/adrns/oso-java-quickstart/tree/feature/reproduce-single-expression-issue) to reproduce this. There's an extra rule that does return what I'm expecting. To examine the results either drop in a breakpoint or just view the response:

`curl localhost:5000/has_intersection_unbound` to reproduce the issue
`curl localhost:5000/has_intersection_unbound_expected` to see what's expected

**Comment by gw000** [comment]
Hi @adrns . I believe you need to pass `allowed_labels` to the recursive `has_intersection` call:

```
has_intersection(owned_labels, allowed_labels) if
  [first, *tail] = owned_labels and
  (has_intersection(tail, allowed_labels) or first in allowed_labels);
```

Calling it with only one argument doesn't invoke the rule you defined and just automatically fails, but `"red"` is bound to `first` by the outer call. That's why you see one result.

**Comment by adrns** [comment]
Hi @gw000,
indeed it yields the expected result, thanks!

(I guess I didn't notice that mistake because there isn't anything that's warning about calling a non-existent function. Turning on e.g. POLAR_LOG=INFO prints it though.)
