### ISSUE TITLE
Syntax highlighting bug in Polar language server

### ISSUE THREAD

**Issue by craigpastro** [osohq/oso#1702]
👋 I am not sure if this is known already, but I copied a polar fragment from your docs into VS Code with the Oso extension installed and it complains about a misplaced "if". Seems like a bug?

![Screenshot 2023-05-11 at 8 58 58 AM](https://github.com/osohq/oso/assets/28915792/496e6ded-cc8c-4deb-804f-3dbe20cc897a)

**Comment by samscott89** [comment]
Hey @craigpastro!

The syntax supported in Oso Cloud and the Oso library differ slightly. The `role if role on "folder"` syntax is only supported in Oso Cloud for now. That'll change as part of #1703, but for now you can toggle which you're using: https://www.osohq.com/docs/reference/more/ide-support#configuration

**Comment by craigpastro** [comment]
Ah, I missed that. Thank you very much!
