### ISSUE TITLE
ruby: JSON trace nesting hinders successful evaluation

### ISSUE THREAD

**Issue by srenatus** [osohq/oso#292]
Hi there! It's been fun to play with oso so far. :smiley:

One observation: the ruby library (probably the other languages as well?) uses JSON to communicate, and running a toy example, I've triggered a case where the **trace** is responsible for an evaluation that otherwise was successful.

My toy code is `fib`:
```
fib(0, 1) if cut;
fib(1, 1) if cut;
fib(n, a+b) if fib(n-1, a) and fib(n-2, b);
```

running this with `oso fib.polar`, and querying `fib(12, x)`, I get:

```
Traceback (most recent call last):
        15: from b/oso:29:in `<main>'
        14: from b/oso:29:in `load'
        13: from /Users/stephan/Misc/oso/languages/ruby/bin/oso:7:in `<top (required)>'
        12: from /Users/stephan/Misc/oso/languages/ruby/lib/oso/polar/polar.rb:96:in `repl'
        11: from /Users/stephan/Misc/oso/languages/ruby/lib/oso/polar/polar.rb:96:in `loop'
        10: from /Users/stephan/Misc/oso/languages/ruby/lib/oso/polar/polar.rb:112:in `block in repl'
         9: from /Users/stephan/Misc/oso/languages/ruby/lib/oso/polar/polar.rb:112:in `to_a'
         8: from /Users/stephan/Misc/oso/languages/ruby/lib/oso/polar/polar.rb:112:in `each'
         7: from /Users/stephan/Misc/oso/languages/ruby/lib/oso/polar/polar.rb:112:in `each'
         6: from /Users/stephan/Misc/oso/languages/ruby/lib/oso/polar/polar.rb:112:in `each'
         5: from /Users/stephan/Misc/oso/languages/ruby/lib/oso/polar/query.rb:115:in `block in start'
         4: from /Users/stephan/Misc/oso/languages/ruby/lib/oso/polar/query.rb:115:in `loop'
         3: from /Users/stephan/Misc/oso/languages/ruby/lib/oso/polar/query.rb:116:in `block (2 levels) in start'
         2: from /Users/stephan/Misc/oso/languages/ruby/lib/oso/polar/ffi/query.rb:60:in `next_event'
         1: from /Users/stephan/.rbenv/versions/2.5.3/lib/ruby/2.5.0/json/common.rb:156:in `parse'
/Users/stephan/.rbenv/versions/2.5.3/lib/ruby/2.5.0/json/common.rb:156:in `parse': nesting of 101 is too deep (JSON::NestingError)
```

I've added a `puts event.to_s` in `lib/oso/polar/ffi/query.rb`, and it looks like it's the `trace` that's too deeply nested. (The `Result` bindings are there, so the query was evaluated successfully.)

Skimming the ruby code, I'm not certain that the trace is actually used; however, I've found no way to have `JSON.parse` ignore a certain key.

Related question: have you considered using different formats for this? (Anything well-supported enough across languages, flatbuffers, protobuf, ...) I'd suspect that there's performance wins here... :thinking:

**Comment by gj** [comment]
Hey @srenatus!

A few of us were playing around with your `fib()` example yesterday and ran into the same issue. You're correct that traces aren't currently used anywhere, and we're going to make them opt-in until we're ready to roll out some features that leverage them properly.

> Related question: have you considered using different formats for this? (Anything well-supported enough across languages, flatbuffers, protobuf, ...) I'd suspect that there's performance wins here... :thinking: 

That is a great idea, and I agree there's definitely some performance fat to trim away there. I'll bring this up with the rest of the team today and get back to you with an update later.

**Comment by gj** [comment]
@srenatus the issue of the trace payload being too deeply-nested and blowing up should be fixed by #298. We're going to do a bugfix release today that will include the fix.

We discussed using a more performant format than JSON, but we're going to stick with JSON for the time being. You're right about the potential for performance wins, but one of the goals for now is to keep the process for standing up new language libraries as simple as possible. I could definitely see us moving toward something like protobufs in the future when the main focus is on optimization.

**Comment by srenatus** [comment]
Thanks for the quick fix. 😃 

> one of the goals for now is to keep the process for standing up new language libraries as simple as possible.

That makes sense! JSON is ubiquitous.

**Comment by gj** [comment]
> Thanks for the quick fix. :smiley:

Thank _you_ for the report :smile:
