### ISSUE TITLE
Go library

### ISSUE THREAD

**Issue by gj** [osohq/oso#459]
We want to add support for Golang.

**Comment by leina05** [comment]
We are releasing an alpha version of the Go library this week! Check it out here: https://pkg.go.dev/github.com/osohq/go-oso@v0.11.0-alpha

We'll be continuing work on the library this sprint and would really love feedback from the Go community. Please add any thoughts here! Or you can always visit us on [Slack](https://oso-oss.slack.com/)

**Comment by gj** [comment]
Today we released a second alpha version that includes support for Windows and registering constructors for use with Oso's [new](https://docs.osohq.com/go/reference/polar-syntax.html#new) operator: https://pkg.go.dev/github.com/osohq/go-oso@v0.11.0-alpha.1

**Comment by gj** [comment]
We released this... a while ago 😅
