### ISSUE TITLE
Question: large no of policies and load changes in policies.

### ISSUE THREAD

**Issue by awemulya** [osohq/oso#492]
How can I implement watcher to detect and update policy without restarting server.
`load_str(polar, "role(user, role_name) if user.role = role_name;", "somefile.policy")`  does not  saves to file.

I have background workers updating policies, assigning role to user in a organization on user creation.
I need to check newly created users  policy.

**Comment by samscott89** [comment]
Hey @awemulya! Thanks for opening an issue.

> How can I implement watcher to detect and update policy without restarting server.

Currently the best way to achieve this is to use whatever is built into your chosen web framework (if using one, and if it has one). For example, in our django-oso integration, we add all `.polar` files to the list of watched files: https://github.com/osohq/oso/blob/main/languages/python/django-oso/django_oso/apps.py#L12

If implementing something like that, it might be useful to know that there is an `Oso.clear_rules` method, which will clear all rules previously added, so you can add more.

>  `load_str(polar, "role(user, role_name) if user.role = role_name;", "somefile.policy")` does not saves to file.

Quick tip: generally speaking you should be interacting with the `oso` instance, like: `oso.load_str("....")`.

`load_str` is used to load policies from a string into the oso _instance_. Not for saving to files (that additional filename argument is probably unhelpful and we should remove it).

In general, we recommend only using `load_file` in an application. `load_str` can be useful in testing to load a policy inline. If you are needing to make updates to the policy file based on user creation, it is better that you store this information in the database, and reference it in the policy. We have a guide on this here: https://docs.osohq.com/using/examples/rbac.html#rbac-with-existing-roles

If you want more help with using oso in your application, you can [come chat to us in slack](https://join-slack.osohq.com). And again, thank you for the feedback + questions

**Comment by awemulya** [comment]
@samscott89 Thank you for your quick response.
