### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by alexvuta** [osohq/oso#589]
Hello there,

I appreciate very much this awesome tool that fits very well with the project I am working on.
I am wondering if there somewhere is planned a integration with font-end (Angular/Typescript) side to validate policies.

Can be very powerful to restrict component access based on roles for example.

Thanks a lot for a such awesome tool and keep going!

**Comment by gj** [comment]
Thank you for the issue! We've done a lot of thinking about this topic, and we have some similar work upcoming on our near-term roadmap to enable authorization-dependent UI elements from the back end. Making those policy decisions on the front end is entirely possible (our WASM-backed Node.js integration will take a bit of tweaking to get it to run in browsers), and is definitely something we'll look at as a follow-up to the initial work.

Do you think authZ-dependent UI elements driven from the back end would work for your use case, at least until we get to the front end work?

We're still working out the order in which we'll prioritize languages and frameworks for the initial work, but any additional details you can provide about your specific use case would be super helpful to us in designing the feature.

You could also join [our Slack workspace](https://join-slack.osohq.com/) if you'd like. We've had people ask similar questions before and have shown them how to achieve it currently.

**Comment by samscott89** [comment]
A couple of updates on this:

- As @gj mentioned, it might be that this use case can be handled from the backend. We're doing some work on that currently, and will update https://github.com/osohq/oso/issues/612 based on that.
- We did manage to get the typescript library working as a browser module too. We will look into distributing that so people can use it. If you have a use case for it, let us know and we can share with you an early version that you can try out!

**Comment by alexvuta** [comment]
Hello :+1:  thanks again !
We (me and the company I work for) plan to buid a oauth2 authentication flow using SSO soon. We don't have yet a complete infrastructure to implement authentication flow but is on our Road-map.
Once we'll get there I will be glad to test the typescript library with our Front-End team in order to provide some useful feedback.

**Comment by gj** [comment]
Hey @alexvuta, I'm gonna close this one in favor of #612.

Would love to hear any feedback you have over there or [on Slack](https://join-slack.osohq.com/)!
