### ISSUE TITLE
Error "inline query result was false", but which one?

### ISSUE THREAD

**Issue by ximon18** [osohq/oso#695]
When using `?= ...` inline queries to verify that a Polar policy behaves as expected, in the event that a query fails the error message output by Oso doesn't indicate the query that failed but only says _"inline query result was false"_. I encountered this with Oso 0.8.1 for Rust but looking at the [`code in the main`](https://github.com/osohq/oso/blob/main/languages/rust/oso/src/oso.rs#L75) branch it seems to be the same:

```rust
    fn check_inline_queries(&mut self) -> crate::Result<()> {
        while let Some(q) = self.inner.next_inline_query(false) {
            let query = Query::new(q, self.host.clone());
            match query.collect::<crate::Result<Vec<_>>>() {
                Ok(v) if !v.is_empty() => continue,
                Ok(_) => return lazy_error!("inline query result was false"),
                Err(e) => return lazy_error!("error in inline query: {}", e),
            }
        }
        check_messages!(self.inner);
        Ok(())
    }
```

Setting environment variable `POLAR_LOG=1` helps a bit as you can work out the last query that was being executed, but it's not that easy as you have to look at the log statement indentation to try and work out where the start of the query execution was and thus what the root query being executed was.

**Comment by samscott89** [comment]
Hey @ximon18!
Thanks for opening an issue with this. You're right, that's not the ideal behaviour here. We return the query on _errors_ but not on evaluating it as false.

I'll add a task in our internal tracker to address this and update you when a fix is in

**Comment by ximon18** [comment]
@samscott89: I just tried this with oso 0.11.2 and it's great, a really big improvement!

```
Inline query failed not allow(new Actor("t2test", { team: "t2", teamrole: "admin" }), PUB_ADMIN, new Handle("ca2")) at line 179, column 3
```

Thanks!
