### ISSUE TITLE
sqlalchemy-oso: get_resource_users_by_role fails when used with a resource not named "repository"

### ISSUE THREAD

**Issue by saschajullmann** [osohq/oso#740]
Hi there,

thank your for an interesting library, it's very much appreciated.
I played around with sqlalchemy-oso today and encountered the following bug:

When you create a ResourceRoleModel between a generic "user" model and a resource that is not named "repository" then trying to get all the users for a specific role on a specific resource fails (e.g. oso_roles.get_resource_users_by_role(
        db_session, organization, "ADMIN"
    )):

`sqlalchemy.exc.InvalidRequestError: Entity '<class 'app.models.organization_role.OrganizationRole'>' has no property 'repository'`

In this case my resource was named "organization". The expectations was that a list of all users with the role "ADMIN" or an empty list was returned, but an exception was raised.

This is due to the fact that in the function "get_resource_users_by_role" the users query has a "filter_by" with a hardcoded "repository" property. 
https://github.com/osohq/oso/blob/38eec0030c2d0c3a941d907d69f7f2241bed7749/languages/python/sqlalchemy-oso/sqlalchemy_oso/roles.py#L405

I can provide a pull request if this is welcome. I verified locally that you can just get the resources name and use that in the filter instead of a hardcoded value.

Let me know what you think.

All the best.

**Comment by samscott89** [comment]
Hey @saschajullmann! Thanks for catching this, opening an issue, and also diagnosing the problem :) 

We would love it if you already have a fix ready to go that you could PR, that would be super helpful.

**Comment by samscott89** [comment]
It sounds like you already have this, but something matching what we've done elsewhere would be good:

https://github.com/osohq/oso/blob/38eec0030c2d0c3a941d907d69f7f2241bed7749/languages/python/sqlalchemy-oso/sqlalchemy_oso/roles.py#L506

**Comment by saschajullmann** [comment]
Hi Sam,

you're right, I did not see this. This is what I did too. I used a different variable name before but matched it to "filter_kwargs" so that it is consistent.

You can find my PR here:
https://github.com/osohq/oso/pull/745

All the best

**Comment by leina05** [comment]
Thank you for the fix @saschajullmann !!
