### ISSUE TITLE
Add `get_allowed_actions()` to non-Python libraries

### ISSUE THREAD

**Issue by leina05** [osohq/oso#746]
[`get_allowed_actions()`](https://github.com/osohq/oso/blob/b7b588cb32a405a1dfdf4c509e05b3e65d173a30/languages/python/oso/oso/oso.py#L43-L79) returns a list of all actions an actor is allowed to take on a resource based on the policy. Currently, this is only implemented in the Python library.

We'd like to add this to the other language libraries:

- [x] Node.js
- [x] Go
- [x] Ruby
- [x] Java
- [x] Rust

**Comment by joshrotenberg** [comment]
- [X] Rust

**Comment by samscott89** [comment]
- [x] Java

Thanks @joshrotenberg !

**Comment by samscott89** [comment]
> 
> 
> -  [x]  Java
> 
> 
> Thanks @joshrotenberg !

 - [x] Go

Thanks @joshrotenberg again!

**Comment by gj** [comment]
As of the 0.20 release that stabilizes tomorrow, `authorized_actions` (the new name for `get_allowed_actions`) has been added to [Ruby](https://github.com/osohq/oso/blob/e7160c3ed4f28e84a5ea6f8da2d761a889f5fe43/languages/ruby/lib/oso/oso.rb#L110-L140) and [Node.js](https://github.com/osohq/oso/blob/e7160c3ed4f28e84a5ea6f8da2d761a889f5fe43/languages/js/src/Oso.ts#L97-L137). 🎉 

Thanks again for all of your contributions @joshrotenberg !
