### ISSUE TITLE
Non-existent attributes still match in a rule head specializer in Node.JS library

### ISSUE THREAD

**Issue by leina05** [osohq/oso#749]
A rule like:
```
allow(actor, action, resource: {attr: attr});
```
still matches even if the object passed in as `resource` does not have the `attr` attribute. This has to do with how the library handles `undefined` (it passed it back into Polar instead of treating it as a failed match).

**Comment by samscott89** [comment]
Is there a distinction in Node between a non-existent attribute and one which is undefined?

e.g.
```js
d = { a: 1 }
d.b
// returns undefined
```

vs

```js
d = { a: 1, b: undefined }
d.b
// also returns undefined
```

**Comment by dhatch** [comment]
```
> x = {b: undefined}
{ b: undefined }
> x.hasOwnProperty("b")
true
> x.hasOwnProperty("b")
true
> x.b
undefined
> x.hasOwnProperty("foo")
false
> x.foo
undefined
```

**Comment by dhatch** [comment]
Should be doing a similar check like this: https://github.com/osohq/oso/blob/main/languages/python/oso/polar/query.py#L98
