### ISSUE TITLE
0.11.0 not released on crates.io?

### ISSUE THREAD

**Issue by ximon18** [osohq/oso#752]
Hi,

Nearly a week ago now v0.11.0 was released according to https://www.osohq.com/post/oso-release-0-11-0 and https://github.com/osohq/oso/releases/tag/v0.11.0, yet the latest release on crates.io is https://crates.io/crates/oso/0.10.1.

Shouldn't 0.11.0 be available via crates.io?

Thanks,

Ximon

**Comment by saolsen** [comment]
Thanks you for letting us know!
Looks like there was a bug in our publish script and this one didn't get pushed. I just pushed it manually so it should be there now, sorry about that.

**Comment by ximon18** [comment]
LGTM!
