### ISSUE TITLE
Can we have dotnet core support?

### ISSUE THREAD

**Issue by Jordan-Hall** [osohq/oso#772]
I really like how this is well structured. But the backend is written in dotnet core. Are they any examples to add support for c# dotnet core?

**Comment by samscott89** [comment]
Hi @Jordan-Hall! Thanks for opening an issue.

We don't currently support .NET but it's something that has come up before: #596. 

Would you mind adding this as a comment over there and maybe voting on that thread? We use community feedback to identify what language/frameworks to support.

**Comment by Jordan-Hall** [comment]
Thank you! i did look but couldn't find one!

**Comment by samscott89** [comment]
No problem! Thank you again.
