### ISSUE TITLE
Rule querying requires `&mut self`, hampering multi-threaded querying

### ISSUE THREAD

**Issue by fisherdarling** [osohq/oso#773]
`query_rule` and `is_allowed` require a mutable borrow on an `Oso` instance. This requires me to create a new instance per route / thread, rather than reusing a global instance.

Question / Issue from the presentation on 3/3

**Comment by samscott89** [comment]
Yep, you're right. Good catch! We've been unnecessarily wrapping things in mutexes.

**Comment by gj** [comment]
This should be fixed as of 0.11.2. Thanks @fisherdarling!
