### ISSUE TITLE
Discussion: One questions about code architecture.

### ISSUE THREAD

**Issue by ZhangHanDong** [osohq/oso#777]
I probably took a look at the code structure of oso. 

The implementation is very good, but there is a question: 

The current unified interface supports OOP,  so how to extend the support of FP language?
Will the current architecture be inconvenient?

If the question is too stupid, please forgive me for not learning the code in depth.

**Comment by samscott89** [comment]
Hey! Thanks for taking a look and for the praise :) 

And no need to apologise! This is a fantastic question. We need to do more exploration and design to be able to answer this conclusively, but here are some initial thoughts I have about why the two should work well together:

First, the Oso policy language (Polar) is logic-based + declarative. I think this actually matches up pretty nicely with functional programming, especially in how they both treat data.

For example, Polar expects most data structures to be immutable. Most FP data structures would work pretty well in Polar. And for languages like Elixir with [structs](https://elixir-lang.org/getting-started/structs.html), this would match up pretty well with how we think about classes.

As a great example of this, we can look at our Rust support. Rust has similarities with FP languages, it doesn't have a class system or OO. The way we make it possible to define "class methods" in Rust, is by associating a function with a particular name. See: https://docs.rs/oso/0.11.0/oso/#example

```rust
oso.register_class(
   User::get_polar_class_builder()
        .add_class_method("superusers", User::superuser)
        .build()
)?;
```

That `add_class_method`  is associating the function `User::superuser`, which just happens to take in one input, to our pseudoclass `User`.

So I think something similar would work for other languages.

The hardest part, generally, in making Oso work with a language is understanding how to do things dynamically. (We wrote about [how we did this for Rust](https://www.osohq.com/post/rust-reflection-pt-1)).

I, unfortunately, don't know Elixir well enough, but something like [this](https://hexdocs.pm/elixir/Kernel.html?#apply/3) might be applicable.

Does that help clarify? Do you have a particular language in mind?
