### ISSUE TITLE
0.11.1 not released on crates.io?

### ISSUE THREAD

**Issue by ximon18** [osohq/oso#781]
Hi,

Similar to #752 I see that in GitHub there was a 0.11.1 release 14 days ago, which includes changes to polar-core, yet the latest release on crates.io is 0.11.0.

Shouldn't 0.11.1 be available via crates.io?

Thanks,

Ximon

**Comment by saolsen** [comment]
Ahh! yeah, same bug. I just pushed 0.11.1 and will actually fix the bug this time #783 sorry about that!

**Comment by ximon18** [comment]
Thanks!
