### ISSUE TITLE
docs/changelogs/ not up-to-date?

### ISSUE THREAD

**Issue by ximon18** [osohq/oso#782]
Hi,

At https://github.com/osohq/oso/tree/main/docs/changelogs the most recent entry is [2021-02-03.rst](https://github.com/osohq/oso/blob/main/docs/changelogs/2021-02-03.rst) which includes:

> This week we are releasing go-oso as an alpha release!

Yet [on February 17th the blog announced](https://www.osohq.com/post/oso-release-0-11-0) that go-oso was now officially released:

> The official release of the Oso Go library is here! go-oso 0.11.0 now supports the REPL, the debugger and has expanded documentation. Get started with go-oso here.

Are these changelog entries supposed to be kept up-to-date? If so, aren't they missing some updates?

Thanks,

Ximon

**Comment by saolsen** [comment]
We've recently rewritten our docs. They live in the `new-docs` folder for now. If you want the source for the changelogs they are here https://github.com/osohq/oso/tree/a71914f62a8eb7f80c0db59018e7f6213ed82468/new-docs/content/any/project/changelogs and get published here https://docs.osohq.com/project/changelogs.html

**Comment by ximon18** [comment]
Thanks. Yes I'd found the new page. I was looking in GitHub to see if the changelog there had anything else interesting to say about the changes to polar-core. Perhaps add a `MOVED.md` file or something to the old directory? I'll close this issue, thanks for responding.
