### ISSUE TITLE
Go - proposal for new (or alternative) class registration syntax

### ISSUE THREAD

**Issue by delicb** [osohq/oso#816]
Now, registering a class requires providing an instance of `reflect.Type`, like so:
```go
osoEngine.RegisterClass(reflect.TypeOf(User{}), nil)
```

Instead of that, I propose passing instances of a type directly, thus removing the need for users of the library to use `reflect` package. Previous call would look like this:
```go
osoEngine.RegisterClass(User{}, nil)
```

Of course, this would be applied to all `Register*` methods. 

I do remember seeing this kind of API in other libraries. Also, while not directly the same use case, some ORM libraries use similar approach as well. 

Regarding implementation, `RegisterClass` could accept `interface{}` and do `reflect.TypeOf` in implementation, so backward compatibility should be preserved regarding function signature. Additionally, it is possible to make a distinction between `reflect.Type` and anything else and adapt, so that existing code would work (of course, if someone needs to register type `reflect.Type` only option would be to pass `reflect.TypeOf(reflect.Type{})`, but I do not expect a lot of Polar policies to use `reflect.Type`).

**Comment by delicb** [comment]
Since #820 is merged, (thanks @saolsen and @gj), I guess this can be closed. Or do you prefer to close tickets once the next version is shipped?

**Comment by gj** [comment]
I'll close this after I make sure you're credited for your contribution in the upcoming release's changelog 🙂
