### ISSUE TITLE
oso cli help

### ISSUE THREAD

**Issue by Anniepoo** [osohq/oso#823]
1. from bash query  `oso --help`
2. EXPECTED: prints help message with command line options for the oso cli tool
3. OBSERVED:
```
nniepoo@anniesasus:~/oso/osopractice$ oso --help
Error: policy files must have the .polar extension. --help does not.
anniepoo@anniesasus:~/oso/osopractice$ 
```

Suggested fix - make -h -help and --help all print a sane error message

**Comment by joshrotenberg** [comment]
It might be overkill if the tool doesn't have much in the way of command line options, but the [clap](https://crates.io/crates/clap) crate is a joy to work with and makes stuff like this easy to deal with.
