### ISSUE TITLE
[Rust] REPL logging needed to see tracing

### ISSUE THREAD

**Issue by Anniepoo** [osohq/oso#824]
The oso REPL  is documented as needing `POLAR_LOG=1` to get explanations

OBSERVED:
You actually need `POLAR_LOG=now` (which prints messages to stderr rather than going through the language binder, is intended as an internal tool for dev work on Polar).
To use `POLAR_LOG=1` you need to turn on `RUST_LOG=1` as well.
EXPECTED:
Agreement between the docs and the actual behavior. `POLAR_LOG=1` should just work.

**Comment by gkaemmer** [comment]
A fix for this will go live in our next release: #1115 -- rust will use stdout to log traces when `POLAR_LOG=1` is set, making it consistent with our other host libraries.
