### ISSUE TITLE
Python `sqlalchemy-oso` for SQLAlchemy 1.4.x?

### ISSUE THREAD

**Issue by moon-bits** [osohq/oso#851]
Hi!

Thanks for that awesome work on the Oso Framework! We are really enjoying working with it!

Currently, we are evaluating whether the `sqlalchemy-oso` library would fit our needs. Are there any plans regarding the new SQLAlchemy 2 update?

Trying to include it in our project leads to the following error message:

`  Because sqlalchemy-oso (0.6.0) depends on sqlalchemy (>=1.3.20,<1.4.0)
   and no versions of sqlalchemy-oso match >0.6.0,<0.7.0, sqlalchemy-oso (>=0.6.0,<0.7.0) requires sqlalchemy (>=1.3.20,<1.4.0).`

Would love to hear from you!

**Comment by leina05** [comment]
Hey @moon-bits, glad to hear you're liking Oso! We are likely going to provide support for 1.4 soon, but we don't have a target date yet. Are you currently using Oso with the base Python package?

**Comment by moon-bits** [comment]
Hey @leina05, yes! We are using Oso with the Python base package. Currently, we are doing the filtering of the data on our own. 

As we noticed that Oso also provides SQLAlchemy filtering, we got curious and wanted to try it out.

So, I guess we just keep waiting! Keep up the good work!

**Comment by gneray** [comment]
Hey @moon-bits it's great to hear that you're using Oso and are interested in data filtering.

We'd love to make `sqlalchemy-oso` work for you. Would you be up for speaking about your use case with us? If so, drop us an email to engineering [at] osohq [dot] com and we can find a time. Hope to talk soon!

**Comment by moon-bits** [comment]
Hi @gneray! Sorry for not answering you sooner!

Basically, our use case is not special:

- We have a database table full of items that belong to different users/customers. 
- if a user retrieves a list of items then the list must only contain those items that belong to the given user.

@leina05 looking through the SQLAlchemy migration guide, there seem to be no breaking changes if the current `sqlalchemy-oso` does not use any deprecated functions that were marked in `1.3` already. 

See: https://docs.sqlalchemy.org/en/14/changelog/migration_20.html

**Comment by gneray** [comment]
Hi @moon-bits, thanks! Are you using any kinds of roles, hierarchies, etc.?

If so, we're working on some new things in the `sqlalchemy-oso` library that could be useful.

**Comment by moon-bits** [comment]
Hi @gneray !

Currently, we don't. But it's on the plan to introduce a RBAC model into the authorization process. 

Happy to hear that there are also new features planned! Is there an ETA on when we could see the library fit for `SQLAlchemy 1.4`?

**Comment by gneray** [comment]
Hi @moon-bits!

Apologies for the delay here. We need to do some testing to see what work will be required to get the library up to 1.4 first. Is there a timeframe that would be meaningful for you that you'd like us to keep in mind?

**Comment by moon-bits** [comment]
> Hi @moon-bits!
> Is there a timeframe that would be meaningful for you that you'd like us to keep in mind?

The sooner the better, but don't feel rushed. I would like to have a secure/safe authorization library than a SQLAlchemy 1.4-comaptible one :smile: 

I'm linking the following pull request https://github.com/osohq/oso/pull/879, as I see there is already some work in progress.

**Comment by gj** [comment]
Shipped #879 earlier today — `sqlalchemy-oso` 0.7.0 will be released 5/26 with SQLAlchemy 1.4 support. 🥳 

Will update (and close) this issue once it's up on PyPI.

**Comment by gj** [comment]
`sqlalchemy-oso` 0.7.0 is up [on PyPI][]!

[on PyPI]: https://pypi.org/project/sqlalchemy-oso/0.7.0/
