### ISSUE TITLE
[NestJS] - Wrap OsoModule as a library

### ISSUE THREAD

**Issue by eltonlau1994** [osohq/oso#862]
First of all, thanks a lot for having such a great RBAC library and tutorials. I am current going to use it other than any of the library else, as it has organization / project-based access control on top of RBAC, which makes my life a lot easier when the app requires multi-tenancy.

However, it indeed needs a bit of the time and learning curve to understand the flow underneath on OsoModule. Therefore, it'd be much better if it can be wrapped as a library and expose limited configurations for end-users.

**Comment by leina05** [comment]
Hey @eltonlau1994! Thanks for opening this. We don't have a NestJS integration yet, but our friends @bjerkio developed one that you might want to check out: https://github.com/bjerkio/nestjs-oso. In the meantime, please let us know if there's anything else we can do to help you use Oso 🙂

**Comment by eltonlau1994** [comment]
@leina05  thanks a lot! The library is really good and easy to use. 
I just realized it was posted in Oso documentation as well: https://docs.osohq.com/node/getting-started/application.html
