### ISSUE TITLE
Memory Leak in Golang

### ISSUE THREAD

**Issue by bhb603** [osohq/oso#944]
Hi OsoHQ,

Been enjoying the library, and I hope to use it for an authorization service, however I believe I found a memory leak in the Golang library.

## Setup

I was able to reproduce using the `oso-go-quickstart` example. I [forked that repo](https://github.com/bhb603/oso-go-quickstart) and the only changes I made were:
- upgraded to the latest oso  `v0.11.3 ->  v0.12.3` (https://github.com/bhb603/oso-go-quickstart/blob/main/go.mod#L5)
- added a policy:
    ```
    allow(actor: String, "GET", expense: Expense) if  
            expense.SubmittedBy = actor;
    ```
- [Dockerized](https://github.com/bhb603/oso-go-quickstart/blob/main/Dockerfile) the app and deployed it to a kubernetes cluster with [this simple deployment](https://github.com/bhb603/oso-go-quickstart/blob/main/k8s/deployment.yaml) (my ultimate use case would be to deploy in kubernetes, which is why I replicated that here)

## Testing

I have some load-testing tooling which can generate requests against the service. Since this quickstart example only has one endpoint, it just requests:
```
curl -H "user: alice@example.com" http://oso-go-quickstart.oso:5050/expenses/1
```
Which would check `oso.IsAllowed(User("alice@example.com"), "GET", expense)` and return:
```
HTTP/1.1 200 OK
Content-Length: 40
Content-Type: text/plain; charset=utf-8

Expense{{500 coffee alice@example.com}}
```

## Results

Memory Usage increases linearly when the service is under load, until it reaches the limit I set for the container (256M) at which point Kubernetes kills the container (OOMKIlled) and it restarts, producing the saw tooth graph below.

The rate of memory increase is proportional to the load (reqs per second), i.e. it increases ~2.5x faster when I was hitting it at 25rps vs 10rps, and flattens out with 0rps.

Memory usage under load:
![Containers___Datadog](https://user-images.githubusercontent.com/4773480/120674575-392cab80-c462-11eb-8c3b-682671ef667b.png)

More Metrics:
![image](https://user-images.githubusercontent.com/4773480/120674630-46499a80-c462-11eb-85cc-1e5635a906e8.png)

**Comment by samscott89** [comment]
Hey @bhb603! Thanks for raising this with us. We're looking into this now and will get back to you ASAP.

**Comment by saolsen** [comment]
Hey, I think I have this figured out.

There is indeed a memory leak! I could reproduce it and I have a fix. My graphs aren't as nice as your Datadog ones so I was wondering if you could try out my fix with your setup and see if it solves the problem.

The fix is pushed to a new alpha tag. `v0.12.4-alpha`, you should just be able to update the `go.mod` dependency to point at it.

**Comment by saolsen** [comment]
Hey @bhb603 , I think I have this figured out.

There is indeed a memory leak! I could reproduce it and I have a fix. My graphs aren't as nice as your Datadog ones so I was wondering if you could try out my fix with your setup and see if it solves the problem.

The fix is pushed to a new alpha tag. `v0.12.4-alpha`, you should just be able to update the `go.mod` dependency to point at it.

**Comment by saolsen** [comment]
`v0.12.4-alpha.1` is the tag to try

**Comment by bhb603** [comment]
Hi @saolsen, appreciate the quick turnaround!

I tried the same test with `v0.12.4-alpha.1`... you definitely fixed a large part of it because it looks **MUCH** better than before, but there does still seem to be a slow leak...

Before the memory ramped up to 256M in ~10minutes, now it looks like that will take about an hour if I let the test continue... but as you can see it is still increasing linearly:

![Containers___Datadog](https://user-images.githubusercontent.com/4773480/120711807-cdf8ce80-c48d-11eb-9eb8-ca2dd69c868a.png)

![image](https://user-images.githubusercontent.com/4773480/120711159-0946cd80-c48d-11eb-88d2-edc03658e54c.png)

**Comment by saolsen** [comment]
Cool, I'll keep hunting for another leak.

**Comment by saolsen** [comment]
Ok @bhb603 I have another build for you. There were indeed more leaks! Try out `v0.12.4-alpha.2`

**Comment by bhb603** [comment]
Looks like you got it! I don't see any indication of leaks in `v0.12.4-alpha.2`:

![image](https://user-images.githubusercontent.com/4773480/120847179-1fae6100-c541-11eb-829c-70c5dd4903a6.png)

Thanks again for the quick response!

**Comment by saolsen** [comment]
Awesome, thanks a lot for running it through your setup, that was extremely helpful! I'll get these changes in and they should be in the next release.

**Comment by ssglaser** [comment]
Hey @bhb603 thanks again for reaching out and helping us make Oso even better! We appreciate you and would love to send you some swag! [Here's a form](https://osohq.typeform.com/to/mIFfkN05) to share details and we'll get it shipped. Thanks again.

**Comment by bhb603** [comment]
@ssglaser thanks I appreciate it!
